### PR TITLE
Add Travis

### PR DESCRIPTION
**Pull request by loicgasser**
@gjn I sent a request to the owner to enable travis some repositories.
What's the owner here?
iwibot?
For coveralls here is the pricing.
Maybe we don't need it as coverage can be red in travis console.
https://coveralls.io/subscriptions/new?for=geoadmin&service=github

### CODE REVIEW

**Comment by gjn** [comment]
Accesses is granted.

If we have to pay, I want to see real benefit first.

**Comment by gjn** [comment]
Jenkins has cobertura plugin to show evolution of coverage. AFAIK, nosetests can output coverage reports in that format. This might be an alternative to coverall.

**Comment by loicgasser** [comment]
Thanks !
Yes I agree I find it pretty expensive. It s free for private repos so that s why I used it.

**Comment by loicgasser** [comment]
I could show you how it works on my account

**Pull request merged**
