### PR TITLE
Flush by bbox

### PR DESCRIPTION
**Pull request by loicgasser**

### CODE REVIEW

**Comment by loicgasser** [comment]
This still works:

```bash
python ./tool_aws/s3/rm.py -b bgdi-tod-cache-dev -p /1.0.0/ch.swisstopo.fixpunkte-agnes/default/current/2056/* -n 2
```

New capabilities:

```bash
python ./tool_aws/s3/rm.py -b ${bucket} -p /1.0.0/ch.swisstopo.fixpunkte-agnes/default/current/2056/* --bbox 2671000,1139000,2712250,1158500 -i png -n 2
```

It should be also faster than before as I spotted a small bug in the multiprocessing code.

Parent pid is always logged now, so that one can make sure the process can be killed easily.
I am think about improving Pool Manager a notch, Keyboard interruption is not super reliable right now, and apparently this is due to a bug in python.
I will try to improve the situation, but at the moment you can simply use

```bash
kill -9 ${parent process pid}
```


Using map_async in poolmanager might be a better solution as I can easily stop/exit the process with a keyboard intterupt event using a timeout hack.
https://stackoverflow.com/questions/1408356/keyboard-interrupts-with-pythons-multiprocessing-pool


https://stackoverflow.com/questions/1408356/keyboard-interrupts-with-pythons-multiprocessing-pool

ping @ltclm

**Comment by ltclm** [comment]
great, thank you loic! i will try to test it a bit.
Which are the resolution limits for the bbox delete?

**Comment by ltclm** [comment]
https://github.com/geoadmin/tool-aws/issues/15

**Comment by ltclm** [comment]
https://github.com/geoadmin/tool-aws/issues/16

**Comment by loicgasser** [comment]
The max bbox is the same as the one defined in gatilgrid.
Thanks for the issues. It's still a fresh dev but it seems to work. If you ommit the srid the script will clear all 4 projections.

**Comment by ltclm** [comment]
which resolutions do you remove with the bbox delete?
min_resolution?
max_resolution?

**Comment by loicgasser** [comment]
All! I will add min/max resolution support. :x

**Comment by loicgasser** [comment]
low res and high res support added, please report any further problem.

**Comment by ltclm** [comment]
great thank you!

**Comment by loicgasser** [comment]
I wouldn t use too many threads until we may change this limit in S3. 2 should be plenty.

**Pull request merged**
